name: Deploy
#actions to do on push to master branch
on:
  push:
    branches:
      - master 
#what jobs to do if there is code push to master branch
jobs:
  deploy:
    runs-on: ubuntu-latest #github machine running the actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 #clone the code from repo to github ubuntu machine

    - name: SSH and deploy #SSH into AWS EC2 instance using key-pair value
      env:
        SECRET_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #Explanation of all 5 commands to run:
        #create a keyfile with the SSH_PRIVATE_KEY value
        #change the permission of the keyfile to 600
        #create a .ssh directory in the ubuntu machine
        #copy the known_hosts file to .ssh directory
        #SSH into the EC2 instance using the keyfile and run the deploy.sh script
      run: |
        echo $SSH_PRIVATE_KEY > keyfile 
        chmod 644 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-54-227-107-206.compute-1.amazonaws.com "sudo bash ~/deploy.sh"

